# Spring Boot 配置文件
spring:
  cloud:
    nacos:
      config:
        server-addr: localhost:8848/nacos
        import-check:
          enabled: false
    gateway:
      routes: # 路由配置
        - id: teaai-ai
          uri: lb://teaai-ai
          predicates:
            - Path=/api/ai/**
        - id: teaai-common
          uri: lb://teaai-common
          predicates:
            - Path=/api/common/**
        - id: teaai-judge
          uri: lb://teaai-judge
          predicates:
            - Path=/api/judge/**
        - id: teaai-question
          uri: lb://teaai-question
          predicates:
            - Path=/api/question/**
        - id: teaai-question-bank
          uri: lb://teaai-question-bank
          predicates:
            - Path=/api/question/bank/**
        - id: teaai-scoring-result
          uri: lb://teaai-scoring-result
          predicates:
            - Path=/api/scoring/result/**
        - id: teaai-service-client
          uri: lb://teaai-service-client
          predicates:
            - Path=/api/service/client/**
        - id: teaai-user
          uri: lb://teaai-user
          predicates:
            - Path=/api/user/**
        - id: teaai-user-answer
          uri: lb://teaai-user-answer
          predicates:
            - Path=/api/user/answer/**
  application:
    name: teaai-gateway
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:

    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    # todo 需替换配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teaai
    username: root
    password: 123456
  # Redis 配置
  redis:
    # todo 需替换配置
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  main:
    web-application-type: reactive # 启用响应式 Web 支持
    allow-bean-definition-overriding: true
server:
  address: 0.0.0.0
  port: 1221
  servlet:
    context-path: /api/gateway
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
knife4j:
  gateway:
    # 启gateway聚合组件
    enabled: true
    # 聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # 开启discover模式
      enabled: true
      # 聚合子服务全部为Swagger2规范的文档
      version: swagger2
  enable: true