# Spring Boot 配置文件
spring:
  application:
    name: teaai-service-client
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      config:
        server-addr: localhost:8848/nacos
        import-check:
          enabled: false
  # session 配置
  session:

    store-type: redis
    # 30 天过期
    timeout: 2592000
    session:
      cookie:
        path: /api
  # 数据库配置
  datasource:
    # todo 需替换配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teaai
    username: root
    password: 123456
  # Redis 配置
  redis:
    # todo 需替换配置
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  main:
    allow-bean-definition-overriding: true
server:
  address: 0.0.0.0
  port: 1229
  servlet:
    context-path: /api/service/client
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
knife4j:
  enable: true
